# $schema: https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
- name: install packages
  community.general.pacman:
    name:
      - neovim
      - lua
      - lua51
      - luarocks
      - lua-luarocks
      - rust
      - go
      - python-pip
      - python-pynvim

- name: install tree-sitter-cli
  community.general.cargo:
    name: tree-sitter-cli

- name: setup config link
  ansible.builtin.file:
    src: "{{ dots_dir }}/.config/nvim"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    state: link
