# $schema: https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/playbook
---
- hosts: localhost
  tasks:
    - name: test
      ansible.builtin.debug:
        var: ansible_facts
