# $schema: https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
- name: install packages
  become: true
  community.general.pacman:
    name:
      - ghostty
      - otf-firamono-nerd

- name: setup link
  ansible.builtin.file:
    src: "{{ dots_dir }}/.config/ghostty"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/ghostty"
    state: link

- name: setup systemd service
  ansible.builtin.systemd_service:
    name: app-com.mitchellh.ghostty.service
    scope: user
    enabled: true
    state: started
